services:
  - type: web
    name: schoolwebsite
    runtime: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn schoolwebsite.asgi:application -k uvicorn.workers.UvicornWorker
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: schoolwebsite-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"

databases:
  - name: schoolwebsite-db
    plan: free
